### ISSUE TITLE
Configuration - Need Help

### ISSUE THREAD

**Issue by Moimemeici** [KircheNeuenburg/ldaporg#26]
It's here can i make new Group ? 

![ldaporg_1](https://user-images.githubusercontent.com/19207283/34824963-dfc43e3a-f6d0-11e7-8083-fa2c1b90bd34.JPG)

![ldaporg_2](https://user-images.githubusercontent.com/19207283/34824987-fb037166-f6d0-11e7-9877-56413dea0080.JPG)

![ldaporg_4](https://user-images.githubusercontent.com/19207283/34825011-148af870-f6d1-11e7-8dd9-7c67b3cad778.JPG)

Sorry but what i need write here ?

![ldaporg_3](https://user-images.githubusercontent.com/19207283/34824991-fd44ce98-f6d0-11e7-9bae-497f635f43ab.JPG)

**Comment by Moimemeici** [comment]
Please can you help me ?

**Comment by alexhor** [comment]
I have started working on an update that will make the app more flexible across different LDAP installations.
This will probably fix you error as well, hold tight.

**Comment by alexhor** [comment]
ok, the newest version is now available in the app store.
I hope this fixes your error.

**Comment by Moimemeici** [comment]
Ok, i go test !

**Comment by Moimemeici** [comment]
Thanks for your work.
