### ISSUE TITLE
Add Group - Modify group

### ISSUE THREAD

**Issue by Moimemeici** [KircheNeuenburg/ldaporg#30]
Hello, sorry for disturb.
I have problem maybe configuration.
Can i add group via Ldap Organisation Group ?
and 
Can i modify group user via Nextcloud User Interface ?
Thank you for your work and sorry for my question.

**Comment by alexhor** [comment]
Always disturb! It can only make the app better :)

You need at least one existing group on your LDAP server.
Then go to "Settings > LDAP / AD Integration > LDAP Org Settings" and set the group as a superuser group.
Then all the users in that group can edit existing and create new groups.

**Comment by Moimemeici** [comment]
Thank's again !
